### ISSUE TITLE
Add region feature to map

### ISSUE THREAD

**Issue by wsalesky** [srophe/bethqatraye#4]
Have Red pins as default
Green pins for any place where:
```
<location type="nested">
<region ref="http://syriaca.org/place/37">Beth Qaṭraye (region)</region>
</location>

```
@davidamichelson will make changes to data first

**Comment by wsalesky** [comment]
Feature added. Just needs data. @davidamichelson

**Comment by davidamichelson** [comment]
@wsalesky LOL, when I asked you if I had already requested this, it turns out I had here in this issue. I am closing this one since it is also issue #20 

Just to clarify, did you write new code for issue #20 or did you just use the code from here?

Please close this issue @wsalesky  if everything is done which I think it is.

**Comment by wsalesky** [comment]
@davidamichelson newish code, as #20 has different and more colored pins.

**Comment by davidamichelson** [comment]
Okay, but the part about 
```
<location type="nested">
<region ref="http://syriaca.org/place/37">Beth Qaṭraye (region)</region>
</location>
```
is the same right? I mean you didn;t write it into the code twice because I forgot :)

**Comment by davidamichelson** [comment]
@wsalesky (Just impressed I came up with the same solution twice :)
